[package]
name = "webviewrust"
version = "0.1.0"
authors = ["Julio Bonon <juliocesarbonon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { version = "0.7" }



