version: "2.4"
services:
  weston:
    image: torizon/weston:2
    # Required to get udev events from host udevd via netlink
    network_mode: host
    environment: 
    - GDK_BACKEND="wayland"
    - DISPLAY=:0
    - ENABLE_VNC=1
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - "c 4:0 rmw"
      # ... for tty7
      - "c 4:7 rmw"
      # ... for /dev/input devices
      - "c 13:* rmw"
      # ... for /dev/dri devices
      - "c 226:* rmw"
  gtkrust: 
    image: reininy/gtkrust
    depends_on: 
      - weston
    privileged: true
    environment:
    - DISPLAY=:0
    volumes:
        - type: bind
          source: /tmp
          target: /tmp
        - type: bind
          source: /dev
          target: /dev
        - type: bind
          source: /run/udev
          target: /run/udev
